input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["live_matches"]
    group_id => "elk-group"
    codec => "json"
  }
}

# filter {
#   # Optionnel : formatage des dates et normalisation
#   date {
#     match => ["date_heure", "ISO8601"]
#     target => "@timestamp"
#   }
# }

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "matches"
  }

  stdout { codec => rubydebug }  # pour debug dans les logs
}
